FROM node:0.12.7-wheezy

MAINTAINER Jialu <zhangjialu@yahoo.com>

#RUN mkdir /myapp

ADD hello.html /
ADD webserver.js /

#RUN npm install express -g
#RUN npm install expressworks -g
WORKDIR /

EXPOSE 7777


